NDefines.NAI.AREA_DEFENSE_SETTING_VP = true
NDefines.NAI.AREA_DEFENSE_SETTING_PORTS = true
NDefines.NAI.AREA_DEFENSE_SETTING_COASTLINES = false
NDefines.NAI.AREA_DEFENSE_MINCAP_MAX_CAPITAL_DEFENSE = 2
NDefines.NAI.AREA_DEFENSE_MINCAP_DESIRED_CAPITAL_DEFENSE = 1
NDefines.NAI.AREA_DEFENSE_MINCAP_MAX_HOME_AREA = 2
NDefines.NAI.AREA_DEFENSE_MINCAP_DESIRED_HOME_AREA = 1



NDefines.NMilitary.MIN_VP_NEEDED_FOR_DEFENSE_ORDER_ASSIGNMENTS = 0.0




NDefines.NAI.AREA_DEFENSE_CAPITAL_PEACE_VP_WEIGHT = { 1.0, 1.0, 1.0 }
NDefines.NAI.AREA_DEFENSE_CAPITAL_VP_WEIGHT = { 1.0, 1.0, 2.0 }
