

NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2
NDefines.NMilitary.MAX_DIVISION_SUPPORT_HEIGHT = 5
NDefines.NMilitary.MAX_REGIMENTAL_SUPPORT_WIDTH = 5
NDefines.NMilitary.MAX_REGIMENTAL_SUPPORT_HEIGHT = 1
NDefines.NMilitary.MAX_HQ_BATTALION_WIDTH = 1
NDefines.NMilitary.MAX_HQ_BATTALION_HEIGHT = 4
NDefines.NMilitary.MAX_HQ_SUPPORT_WIDTH = 1
NDefines.NMilitary.MAX_HQ_SUPPORT_HEIGHT = 4
NDefines.NMilitary.MAX_HQ_REGIMENTAL_SUPPORT_WIDTH = 0
NDefines.NMilitary.MAX_HQ_REGIMENTAL_SUPPORT_HEIGHT = 0
NDefines.NMilitary.REGIMENTAL_SUPPORT_REQUIRED_BATTALIONS = { 3 }
