NDefines.NNavy.AGGRESSION_LEVEL_BY_MISSION_WEAKER[2] = 0
NDefines.NNavy.AGGRESSION_LEVEL_BY_MISSION_STRONGER_OR_EQUAL[2] = 1
NDefines.NNavy.AGGRESSION_LEVEL_BY_MISSION_WEAKER[10] = 0
NDefines.NNavy.AGGRESSION_LEVEL_BY_MISSION_STRONGER_OR_EQUAL[10] = 1

NDefines.NAI.MIN_INVASION_UNITS_READY_TO_EXECUTE = 0.75
NDefines.NAI.INVASION_UNITS_READY_AT_MAX_PLAN = 0.75
